Mustafin Routes
mipt-backend-academy-winter-2023/team-5 pull request #10
Opened 2023-09-17 17:40 UTC by Artemmm91

2023-09-25 16:08 UTC, vovapolu requested changes
нужно добавить opea-api yaml файл для http api

еще нужно поправить пару мелочей, в остальном :+1:

2023-09-25 16:08 UTC, vovapolu commented on repository/src/main/scala/repository/db/NodesImpl.scala
> +      .where(fId > 0)
а зачем?

2023-09-25 16:08 UTC, vovapolu commented on routing/src/main/scala/routing/api/HttpRoutes.scala
>    private def route(credentials: List[IdMapPoint]): Response = {
почему credentials это точки?

2023-09-25 16:08 UTC, vovapolu commented on routing/src/main/scala/routing/api/HttpRoutes.scala
> +        .searchRoute(credentials.head.value, credentials.apply(1).value)
мне кажется, в задании имелось в виду, что нужно найти маршрут по всем точками из списка 1 -> 2 -> 3 -> 4 ...

2023-09-25 16:08 UTC, vovapolu commented on routing/src/main/scala/routing/graph/CityGraphImpl.scala
> +        return path.toList
давайте без return, в скале он не используется

2023-09-25 16:08 UTC, vovapolu commented on routing/src/main/scala/routing/graph/CityGraphImpl.scala
> +  private var _nodes: Map[Int, Node] = Map()
эти параметры можно передавать в функцию или в конструктор класса, в скале не используется инкапсулирование в таком виде

2023-09-25 16:08 UTC, vovapolu commented on routing/src/main/scala/routing/api/HttpRoutes.scala
> +        .searchRoute(credentials.head.value, credentials.apply(1).value)
мне кажется, в задании имелось в виду, что нужно найти маршрут по всем точками из списка 1 -> 2 -> 3 -> 4 ...

2023-10-02 18:14 UTC, Artemmm91 commented on routing/src/main/scala/routing/api/HttpRoutes.scala
> +        .searchRoute(credentials.head.value, credentials.apply(1).value)
поставил заглушку на массив большего размера

2023-10-02 18:14 UTC, Artemmm91 commented on routing/src/main/scala/routing/api/HttpRoutes.scala
> +        .searchRoute(credentials.head.value, credentials.apply(1).value)
поставил заглушку на массив большего размера

2023-10-09 08:18 UTC, vovapolu commented
2 балла + 1 балл за сдачу до первого дедлайна

2023-10-09 08:18 UTC, closed without merging