add upload images
mipt-backend-academy-winter-2023/team-5 pull request #11
Opened 2023-10-01 17:16 UTC by Onyad

2023-10-02 12:23 UTC, vovapolu commented
- В задании предполагалось сделать новый отдельный сервис для загрузки фотографий

- Фотографии должны сопоставляться узлам

- Также должен быть эндпоинт для получения фотографий по узлу

2023-10-02 12:23 UTC, vovapolu requested changes
- В задании предполагалось сделать новый отдельный сервис для загрузки фотографий
- Фотографии должны сопоставляться узлам
- Также должен быть эндпоинт для получения фотографий по узлу

2023-10-12 08:08 UTC, vovapolu commented on project/Libs.scala
> +  val http4s_dsl = "0.23.18"
эти версии должны быть одинаковые

nit

2023-10-12 08:17 UTC, vovapolu requested changes
поправь эти замечания, и поставлю 2 балла :)

2023-10-12 08:17 UTC, vovapolu commented on images/src/main/scala/images/api/HttpRoutes.scala
> +          if req.contentType.contains(
если эти условия не соблюдаются, то приложение выкинет эксепшен, хочется нормальную http ошибку

2023-10-12 08:17 UTC, vovapolu commented on images/src/main/scala/images/api/HttpRoutes.scala
> +        if (!Files.exists(imagePath)) {
этот иф ничего не делает, он не вернет результат

2023-10-22 13:07 UTC, Onyad commented on images/src/main/scala/images/api/HttpRoutes.scala
> +        if (!Files.exists(imagePath)) {
Исправил

2023-10-22 13:07 UTC, Onyad commented on images/src/main/scala/images/api/HttpRoutes.scala
> +          if req.contentType.contains(
Исправил

2023-10-22 13:08 UTC, Onyad commented on project/Libs.scala
> +  val http4s_dsl = "0.23.18"
Исправил

2023-10-23 12:12 UTC, merged

2023-10-23 12:14 UTC, vovapolu commented
ставлю 2 балла, изначально задание было выполнено неверно