Khoruzhi jpeg verification
mipt-backend-academy-winter-2023/team-5 pull request #13
Opened 2023-10-08 18:11 UTC by Onyad

2023-10-09 08:40 UTC, vovapolu commented
замечание с прошлого MR: работа с изображениями должна быть в отдельном сервисе

без этого я не приму домашку

2023-10-22 13:10 UTC, Onyad commented
Исправил прошлую домашку

2023-10-23 12:15 UTC, vovapolu requested changes

2023-10-23 12:15 UTC, vovapolu commented on images/src/main/scala/images/api/HttpRoutes.scala
> +        val jpegValidationResult = req.body.asStream.through(JpegValidation.pipeline).runDrain
гм, это точно будет работать? не будет загрузки всего изображения в память? и стрим прочитается два раза? `req.body.asStream`

2023-10-23 12:15 UTC, vovapolu commented on images/src/main/scala/images/api/HttpRoutes.scala
> +        val jpegValidationResult = req.body.asStream.through(JpegValidation.pipeline).runDrain
я забыл опубликовать этот коммент, извини

можешь посмотреть?

2023-10-23 12:15 UTC, vovapolu commented
сделай ребейз, пожалуйста

2023-11-07 11:41 UTC, merged

2023-11-07 11:42 UTC, vovapolu commented
все хорошо, ставлю 2 балла за неверное изначальное решение и долгое выполнение