docker
mipt-backend-academy-winter-2023/team-5 pull request #3
Opened 2023-05-02 20:52 UTC by Artemmm91

2023-05-05 15:15 UTC, vovapolu requested changes

2023-05-05 15:15 UTC, vovapolu commented on docker-compose.yml
> +    image: project-mipt:latest
получатся одинаковые image для разных приложений?

2023-05-05 15:15 UTC, vovapolu commented on docker-compose.yml
> +      - APP_ENV=production
непонятно, на что влияет эта переменная :)

2023-05-05 15:15 UTC, vovapolu commented on Dockerfile-routing
> +EXPOSE 8080
в docker-compose пробрасывается 8081 порт

2023-05-12 08:43 UTC, Artemmm91 commented on docker-compose.yml
> +    image: project-mipt:latest
поправил

2023-05-12 08:43 UTC, Artemmm91 commented on docker-compose.yml
> +      - APP_ENV=production
убрал

2023-05-13 16:46 UTC, vovapolu approved these changes

2023-05-13 16:46 UTC, merged