Mustafin DB
mipt-backend-academy-winter-2023/team-5 pull request #6
Opened 2023-05-14 11:25 UTC by Artemmm91

2023-05-15 21:50 UTC, p1rattttt requested changes

2023-05-15 21:50 UTC, p1rattttt commented on auth/src/main/scala/auth/repo/UserRepositoryImpl.scala
> +  override def add(user: User): ZIO[Any, Throwable, Unit] = {
если уже был зарегестрирован ("p1rat", "1234"), то может прийти другой юзер и зарегестрировать ("p1rat", "228")
То есть, нет никакой проверки, что логин уже занят

2023-05-18 09:30 UTC, vovapolu commented
нужен ребейх или мердж мастера

2023-05-18 09:46 UTC, vovapolu requested changes

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/resources/db/migration/V2__create_user_table.sql
> +    "id"         SERIAL,
это поле лучше сделать PRIMARY KEY

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/api/HttpRoutes.scala
> +    val key = "secretKey"
лучше вынести в конфиг или во внешнюю константу

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/api/HttpRoutes.scala
> +                ZIO.logInfo(s"Login ${arr.head}")
если найденных юзеров несколько – это очень подозрительная ситуация, лучше выдавать ошибку и не логгировать пользователя

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/api/HttpRoutes.scala
> +                Response.text(s"{\"token\": \"${generateJwtToken(arr.head.login)}\"}")
json лучше генерировать с помощью circe, а не через строку

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/config/Config.scala
> +        serverConfig <- ZIO.service[DbConfig]
for с одной строчкой лучше переписать на .map

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/config/Config.scala
> +case class ConfigImpl(
это не совсем Implementation, почему бы не вынести case class Config наверх?

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/model/JsonProtocol.scala
> +  implicit val userDecoder: Decoder[User] = deriveDecoder
тайпклассы можно выносить в object User, плюс такого подхода, что тайпклассы будут автоматически подтягиваться без каких-либо импортов

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/repo/UserRepository.scala
> +  def find(user: User): ZStream[Any, Throwable, User]
не очень понятно, зачем тут стрим, пользователей не должно быть много при поиске

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/repo/UserRepositoryImpl.scala
> +  def EncryptPassword(password: String): String = {
почему с большой буквы?

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/repo/UserRepositoryImpl.scala
> +    val crypt = java.security.MessageDigest.getInstance("SHA-1")
https://crypto.stackexchange.com/questions/48289/how-secure-is-sha1-what-are-the-chances-of-a-real-exploit

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/repo/UserRepositoryImpl.scala
> +  def EncryptPassword(password: String): String = {
по-хорошему еще нужна соль

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/repo/UserRepositoryImpl.scala
> +  override def add(user: User): ZIO[Any, Throwable, Unit] = {
это можно исправить на уровне бд, через primary key

2023-05-18 09:46 UTC, vovapolu commented on auth/src/main/scala/auth/repo/UserRepositoryImpl.scala
> +  override def add(user: User): ZIO[Any, Throwable, Unit] = {
либо через unique

2023-05-18 09:46 UTC, vovapolu commented on build.sbt
> +      case ("spring.schemas" :: Nil) | ("spring.handlers" :: Nil) =>
spring?

2023-05-25 19:28 UTC, vovapolu commented on auth/src/main/scala/auth/config/ServiceConfig.scala
> +  val secretKey: String = serviceConfig.secret
необычное решение :)

2023-09-16 08:40 UTC, vovapolu approved these changes

2023-09-16 08:41 UTC, merged