Khoruzhii db
mipt-backend-academy-winter-2023/team-5 pull request #7
Opened 2023-05-14 17:59 UTC by Onyad

2023-05-18 09:48 UTC, vovapolu commented
нужно поправить конфликты с мастером – ребейзнуть или смержить мастер

2023-05-18 10:03 UTC, vovapolu requested changes

2023-05-18 10:03 UTC, vovapolu commented on auth/src/main/scala/auth/AuthMain.scala
> +    println("Hello world 1")
println удоляем

2023-05-18 10:03 UTC, vovapolu commented on auth/src/main/scala/auth/api/HttpRoutes.scala
> +        } yield (Response.json(AuthorizationToken(JwtUtils.generateJwt(User(user.login, user.password))).toJson)))
лучше передавать в generateJwt только username, незакодированный пароль – опасная штука

2023-05-18 10:03 UTC, vovapolu commented on build.sbt
> +lazy val repository = (project in file("repository"))
а что означает название repository? первый раз вижу такое название модуля

2023-05-18 10:03 UTC, vovapolu commented on build.sbt
> +ThisBuild / assemblyMergeStrategy := {
а откуда у вас такая простыня assemblyMergeStrategy?

2023-05-18 10:03 UTC, vovapolu commented on project/Libs.scala
> +    "org.postgresql" % "postgresql" % "42.5.4"
раз у нас везде версии, тут тоже лучше вынести версию в V

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/resources/db/migration/V1__user_table.sql
> +    id serial,
нужен primary key в таблице

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/resources/db/migration/V1__user_table.sql
> +    password_hash varchar
важно указывать not null у нужных колонок

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/resources/db/migration/V1__user_table.sql
> +insert into users (username, password_hash) values ('timk', 'verystrongpassword');
какому паролю соотвествует хеш `verystrongpassword`?

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/scala/repository/Config.scala
> +  private val source = ConfigSource.default.at(basePath)
можно заинлайнить basePath

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/scala/repository/Config.scala
> +      for {
for с одним выражением лучше заменить на .map

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/scala/repository/db/Users.scala
> +  def findByUsername(user: User): ZStream[Users, Throwable, User] =
одинаковые методы findByCredentials и findByUsername

2023-05-18 10:03 UTC, vovapolu commented on repository/src/main/scala/repository/db/UsersImpl.scala
> +        case _ => ZIO.succeed(true)
несколько найденных пользователей – очень подозрительная ситуация, лучше выдавать ошибку

2023-05-18 10:32 UTC, Onyad commented on auth/src/main/scala/auth/api/HttpRoutes.scala
> +        } yield (Response.json(AuthorizationToken(JwtUtils.generateJwt(User(user.login, user.password))).toJson)))
Там строчкой выше вызывается PasswordEncode.encode

2023-05-18 10:34 UTC, Onyad commented on build.sbt
> +lazy val repository = (project in file("repository"))
назвал как назвалось, просто к пользователям должен быть доступ и из routing и из auth, значит это надо вынести в отдельный, поэтому вынес

а repository вроде переводится как место куда что-то можно сложить :)

2023-05-18 10:35 UTC, Onyad commented on build.sbt
> +ThisBuild / assemblyMergeStrategy := {
Это прислали в чатике, сказали что это фиксит какую-то проблему, поэтому чтобы даже не увидеть ее, я вставил

2023-05-24 05:16 UTC, Onyad commented on auth/src/main/scala/auth/AuthMain.scala
> +    println("Hello world 1")
+

2023-05-24 05:16 UTC, Onyad commented on auth/src/main/scala/auth/api/HttpRoutes.scala
> +        } yield (Response.json(AuthorizationToken(JwtUtils.generateJwt(User(user.login, user.password))).toJson)))
+

2023-05-24 05:17 UTC, Onyad commented on project/Libs.scala
> +    "org.postgresql" % "postgresql" % "42.5.4"
\+

2023-05-24 05:17 UTC, Onyad commented on repository/src/main/resources/db/migration/V1__user_table.sql
> +insert into users (username, password_hash) values ('timk', 'verystrongpassword');
заменил

2023-05-24 05:17 UTC, Onyad commented on repository/src/main/scala/repository/Config.scala
> +  private val source = ConfigSource.default.at(basePath)
\+

2023-05-24 05:18 UTC, Onyad commented on repository/src/main/scala/repository/Config.scala
> +      for {
\+

2023-05-24 05:18 UTC, Onyad commented on repository/src/main/scala/repository/db/Users.scala
> +  def findByUsername(user: User): ZStream[Users, Throwable, User] =
Пофиксил, не понимаю как я не заметил это когда тестировал

2023-05-24 05:18 UTC, Onyad commented on repository/src/main/scala/repository/db/UsersImpl.scala
> +        case _ => ZIO.succeed(true)
Добавил проверку

2023-09-16 09:08 UTC, vovapolu approved these changes

2023-09-16 09:08 UTC, merged